apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  labels:
    app: {{ .Values.appName }}
data:
  APP_NAME: {{ .Values.appName }}
  ENVIRONMENT: {{ .Values.environment }}
  VERSION: {{ .Values.image.tag }}